---
# Synopsis: Public IP must match our standard 'pip-{enviroment}-{region}-000'
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: 'Org.Naming.Value'
spec:
  type:
    - Microsoft.Network/publicIPAddresses
  condition:
    allOf:
      - name: .
        match: '^pip-(prod|test|dev)-(sc|weu)-\d{3}$'