# This is a basic workflow to help you get started with Actions

name: Analyze IaC

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    #env:
    #  PSRULE_AZURE_BICEP_PATH: '/usr/local/bin/bicep' #if bicep is not able to be fetched
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run analysis by using the PSRule GitHub action.
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.8.1
        with:
          modules: PSRule.Rules.Azure
